#!/usr/bin/env bash

set -o xtrace

function out(){
  echo "$1" >> "$HIE_BIOS_OUTPUT"
}

if [ "$1" == "--interactive" ]; then
  out "$(pwd)"
  for arg in "$@"; do
    out "$arg"
  done
else
  "${HIE_BIOS_GHC:-ghc}" "${HIE_BIOS_GHC_ARGS}" "$@"
fi
